controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - a_palm_link1_joint
      - a_link1_link2_joint
      - a_link2_link3_joint
      - b_palm_link1_joint
      - b_link1_link2_joint
      - b_link2_link3_joint
      - c_palm_link2_joint_0
      - c_link2_link3_joint
initial:  # Define initial robot poses per group
#  - group: hand
#    pose: home

  []