controller_list:
  - name: fake_R_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
  - name: fake_L_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
  - name: fake_R_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - R_drive_joint
  - name: fake_L_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - L_drive_joint
  - name: fake_up_down_controller
    type: $(arg fake_execution_type)
    joints:
      - hand_joint
  - name: fake_head_cam_controller
    type: $(arg fake_execution_type)
    joints:
      - servo_link1_joint
      - servo_link2_joint
initial:  # Define initial robot poses per group
  - group: R_arm
    pose: salute