left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - L_joint1
    - L_joint2
    - L_joint3
    - L_joint4
    - L_joint5
    - L_joint6
    - left_arm_joint
    - L_world_joint
    - L_joint_eef
  gains:
    L_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_world_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L_joint_eef:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - R_joint1
    - R_joint2
    - R_joint3
    - R_joint4
    - R_joint5
    - R_joint6
    - right_arm_joint
    - R_world_joint
    - R_joint_eef
  gains:
    R_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_world_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R_joint_eef:
      p: 100
      d: 1
      i: 1
      i_clamp: 1